name: Deploy Jekyll with PDF compilation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install typst
        run: sudo snap install typst
      
      - name: Compile .typ files to PDF
        run: |
          find ./docs -name "*.typ" -type f | while read typ_file; do
            pdf_file="${typ_file%.typ}.pdf"
            echo "Compiling $typ_file to $pdf_file"
            typst compile "$typ_file" "$pdf_file"
          done
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./WebSite
          destination: ./_site
          additional_config: |
            include:
              - docs
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4