jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install typst
        run: sudo snap install typst
      
      - name: Compile .typ files to PDF
        run: |
          find ./docs -name "*.typ" -type f | while read typ_file; do
            pdf_file="${typ_file%.typ}.pdf"
            echo "Compiling $typ_file to $pdf_file"
            typst compile "$typ_file" "$pdf_file"
          done
      
      - name: Copy docs to WebSite for Jekyll
        run: |
          cp -r ./docs ./WebSite/docs
          echo "WebSite structure:"
          find ./WebSite -type f | sort
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./WebSite
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3